# Import Library

In [37]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
import pandas as pd
import numpy as np

# Import Dataset

In [38]:
# Membaca data dari file CSV menggunakan pandas
data = pd.read_csv('https://raw.githubusercontent.com/dsty13/dataset/main/brain_stroke.csv')
data

gender   age  hypertension  heart_disease ever_married      work_type  \
0       Male  67.0             0              1          Yes        Private   
1       Male  80.0             0              1          Yes        Private   
2     Female  49.0             0              0          Yes        Private   
3     Female  79.0             1              0          Yes  Self-employed   
4       Male  81.0             0              0          Yes        Private   
...      ...   ...           ...            ...          ...            ...   
4976    Male  41.0             0              0           No        Private   
4977    Male  40.0             0              0          Yes        Private   
4978  Female  45.0             1              0          Yes       Govt_job   
4979    Male  40.0             0              0          Yes        Private   
4980  Female  80.0             1              0          Yes        Private   

     Residence_type  avg_glucose_level   bmi   smoking_status  stroke  
0             Urban             228.69  36.6  formerly smoked       1  
1             Rural             105.92  32.5     never smoked       1  
2             Urban             171.23  34.4           smokes       1  
3             Rural             174.12  24.0     never smoked       1  
4             Urban             186.21  29.0  formerly smoked       1  
...             ...                ...   ...              ...     ...  
4976          Rural              70.15  29.8  formerly smoked       0  
4977          Urban             191.15  31.1           smokes       0  
4978          Rural              95.02  31.8           smokes       0  
4979          Rural              83.94  30.0           smokes       0  
4980          Urban              83.75  29.1     never smoked       0  

[4981 rows x 11 columns]

# Encoder data Kategorikal Menjadi data Numerik

In [39]:
kolom = ['gender','ever_married','work_type','Residence_type','smoking_status']
encoder = LabelEncoder()
for k in kolom :
    data[k]=encoder.fit_transform(data[k])
    
data    

gender   age  hypertension  heart_disease  ever_married  work_type  \
0          1  67.0             0              1             1          1   
1          1  80.0             0              1             1          1   
2          0  49.0             0              0             1          1   
3          0  79.0             1              0             1          2   
4          1  81.0             0              0             1          1   
...      ...   ...           ...            ...           ...        ...   
4976       1  41.0             0              0             0          1   
4977       1  40.0             0              0             1          1   
4978       0  45.0             1              0             1          0   
4979       1  40.0             0              0             1          1   
4980       0  80.0             1              0             1          1   

      Residence_type  avg_glucose_level   bmi  smoking_status  stroke  
0                  1             228.69  36.6               1       1  
1                  0             105.92  32.5               2       1  
2                  1             171.23  34.4               3       1  
3                  0             174.12  24.0               2       1  
4                  1             186.21  29.0               1       1  
...              ...                ...   ...             ...     ...  
4976               0              70.15  29.8               1       0  
4977               1             191.15  31.1               3       0  
4978               0              95.02  31.8               3       0  
4979               0              83.94  30.0               3       0  
4980               1              83.75  29.1               2       0  

[4981 rows x 11 columns]

# Normalisasi Min-Max

In [40]:
k_minmax=['age','avg_glucose_level','bmi']

In [41]:
scaler_minmax = MinMaxScaler()

In [42]:
data[k_minmax] = scaler_minmax.fit_transform(data[k_minmax])

In [43]:
data

gender       age  hypertension  heart_disease  ever_married  work_type  \
0          1  0.816895             0              1             1          1   
1          1  0.975586             0              1             1          1   
2          0  0.597168             0              0             1          1   
3          0  0.963379             1              0             1          2   
4          1  0.987793             0              0             1          1   
...      ...       ...           ...            ...           ...        ...   
4976       1  0.499512             0              0             0          1   
4977       1  0.487305             0              0             1          1   
4978       0  0.548340             1              0             1          0   
4979       1  0.487305             0              0             1          1   
4980       0  0.975586             1              0             1          1   

      Residence_type  avg_glucose_level       bmi  smoking_status  stroke  
0                  1           0.801265  0.647564               1       1  
1                  0           0.234512  0.530086               2       1  
2                  1           0.536008  0.584527               3       1  
3                  0           0.549349  0.286533               2       1  
4                  1           0.605161  0.429799               1       1  
...              ...                ...       ...             ...     ...  
4976               0           0.069384  0.452722               1       0  
4977               1           0.627966  0.489971               3       0  
4978               0           0.184194  0.510029               3       0  
4979               0           0.133044  0.458453               3       0  
4980               1           0.132167  0.432665               2       0  

[4981 rows x 11 columns]

In [44]:
X = data.drop(['stroke'], axis=1)
y = data['stroke']

#Splitting Data

In [45]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=21)


# Naive Bayes

In [46]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

In [47]:
y_pred = classifier.predict(X_test) 
y_pred

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,

In [48]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
from sklearn.metrics import accuracy_score 
print ("Accuracy : ", accuracy_score(y_test, y_pred))
cm

Accuracy :  0.8625877632898696


array([[840, 108],
       [ 29,  20]])

In [49]:
data = pd.DataFrame({'Real Values':y_test, 'Predicted Values':y_pred})
data

Real Values  Predicted Values
3709            0                 0
38              1                 1
1842            0                 0
3458            0                 0
3564            0                 0
...           ...               ...
732             0                 0
3039            0                 0
3497            0                 0
242             0                 0
2874            0                 0

[997 rows x 2 columns]

# MLP

In [50]:
from sklearn.neural_network import MLPClassifier
clf = MLPClassifier(hidden_layer_sizes=(100,100,100), max_iter=1000, alpha=0.0001,
                     solver='sgd', verbose=10,  random_state=21,tol=0.001)

In [51]:
clf.fit(X_train, y_train)
y_pred=clf.predict(X_test)

Iteration 1, loss = 0.68570541
Iteration 2, loss = 0.42119269
Iteration 3, loss = 0.29113840
Iteration 4, loss = 0.24022820
Iteration 5, loss = 0.22162311
Iteration 6, loss = 0.21387402
Iteration 7, loss = 0.21098860
Iteration 8, loss = 0.20943509
Iteration 9, loss = 0.20862053
Iteration 10, loss = 0.20812986
Iteration 11, loss = 0.20775082
Iteration 12, loss = 0.20742490
Iteration 13, loss = 0.20715512
Iteration 14, loss = 0.20689238
Iteration 15, loss = 0.20659110
Iteration 16, loss = 0.20633766
Iteration 17, loss = 0.20609022
Iteration 18, loss = 0.20583707
Iteration 19, loss = 0.20560226
Training loss did not improve more than tol=0.001000 for 10 consecutive epochs. Stopping.


In [52]:
accuracy_score(y_test, y_pred)

0.950852557673019

In [53]:
data = pd.DataFrame({'Real Values':y_test, 'Predicted Values':y_pred})
data

Real Values  Predicted Values
3709            0                 0
38              1                 0
1842            0                 0
3458            0                 0
3564            0                 0
...           ...               ...
732             0                 0
3039            0                 0
3497            0                 0
242             0                 0
2874            0                 0

[997 rows x 2 columns]

# KNN

In [54]:
from sklearn.neighbors import KNeighborsClassifier

In [55]:
knn = KNeighborsClassifier(n_neighbors= 11, metric = "euclidean")
knn.fit(X_train, y_train)

KNeighborsClassifier(metric='euclidean', n_neighbors=11)

In [56]:
y_pred = knn.predict(X_test)

In [57]:
knn_accuracy = accuracy_score(y_test,y_pred)
print("Akurasi:", knn_accuracy)

Akurasi: 0.950852557673019


# Decision Tree

In [58]:
from sklearn.tree import DecisionTreeClassifier

In [59]:
clf_gini = DecisionTreeClassifier(criterion='gini', max_depth=3, random_state=42)
clf_gini.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=3, random_state=42)

In [60]:
y_pred_gini = clf_gini.predict(X_test)

In [61]:
from sklearn.metrics import accuracy_score
print('Model accuracy score with criterion gini index: {0:0.2f}'. format(accuracy_score(y_test, y_pred_gini)))

Model accuracy score with criterion gini index: 0.95


In [62]:
y_pred_train_gini = clf_gini.predict(X_train)
y_pred_train_gini

array([0, 0, 0, ..., 0, 0, 0])

In [63]:
print('Training set score: {:.2f}'.format(clf_gini.score(X_train, y_train)))
print('Test set score: {:.2f}'.format(clf_gini.score(X_test, y_test)))

Training set score: 0.95
Test set score: 0.95
